### PR TITLE
times-test

### PR DESCRIPTION
**Pull request by ruihuang888**
Answers UCL-COMP0233-22-23/RSE-Classwork#18

studied how to use times library and how to write a test

Answers UCL-COMP0233-22-23/RSE-Classwork#19

### CODE REVIEW

**Comment by harveymannering** [comment]
Answers https://github.com/UCL-COMP0233-22-23/RSE-Classwork/issues/18

**Comment by ruihuang888** [comment]
Answers UCL-COMP0233-22-23/RSE-Classwork#20

**Comment by ruihuang888** [comment]
Answers UCL-COMP0233-22-23/RSE-Classwork#21

**Comment by ruihuang888** [comment]
Answers UCL-COMP0233-22-23/RSE-Classwork#22

**Pull request closed without merging**
